#!/usr/bin/env python

import sys

from bayesian_class.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'bayesian_class'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
